travis:
  secure:
    BINSTAR_TOKEN: X6os5OD14nXZtHuicJE4WhPlLB9LZsSlyZqz8AecvoQlkdjjWLx0suyDjL836OyFR8Q+rGQvBLlx29pJ6oplSb/wYaN5bdlFhLzKKlnH9rhCfcRX/j/V2P1PSOOUg1Kq5sriT1UQBxFUSJ2koV6t8AW6O3PS6LQAeNzltsYAmewvO6wGQRuZxUday+eewA4et9pF58xhwqd7fq2HaxPb49EeX8vPoBm4BR+V9x4nRKHDFgh+nKNovqunSba8gvAaFe88c6rGKTCqKXEX42qRoPuTVIECAuVnu+SRAL4IMWTYq3XoA9c3a6cXGanIBncWLlVYoj/yWrajTatEitUkBzSzwUMXb5MzFFAoUeayB6KeROMY7pK854bYtaAItEoScukupe5WSEFdnfwmfkcGwYKyRQkyRlCQ89jzsJgTMHIzwC0fBYXPv9Iae1wiVE5zi3kzwVqvBGu2xObsJRyoo7YlazkM8YfwYhDog9RdN/DRQXiofSV8hHxQjEnbIBYV/OupUwxybt3EoR0CHtSq5lLv9/30GbxQWtCHXA71MWxGgNoQtxz7JLQI7RIjc1xxa0mCow6rTjoMxNEIRnHqJBims6ivOTO+B+bqEAaKlTQGHCT7C1wX6MIz2JTCLKAE+O98W3/dJ4nAFg5e+Wqx8nxsnvY9X2EVQD+hydg3Kio=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
