travis:
  secure:
    BINSTAR_TOKEN: QrdFBx+6d1eFMvE5/lywr0lIzrcH9BHxM1hmPXK0dW2XMAeLPfbgGsN0T7NocJYLHTltMChW760O0oh2LPNdfUNApZUBL6/QA/O3FI4qB9dBC7uxNTWqtU/j3dhEQS/CYJRbpi+vALhACvFdSNTmQxhkwxL1Zszj6rNkBEdHB3oPkYHGDRyvt3vwcnSVaeDfydJoWboPmMXci64ZjNbMywOXyoDYylOOKjCBW8ax3Zwasstpvy2i4qXOFmWAYFg8K5pG2vROmHBuw437WzEND9nGjMqAlFsgANz9B0Iw/C45gPGDEuomseVw8upMvxns78f1mV+kM7jg/XJ/TvzMoyGHigAwZimj0MvMdgMo7tZp2l6ea4g8n4ugh51mzYhvBPcOeTrwecwH7/RhIrdssFgL0IsgNzpWESRPBCoQJd7rfXmRw/503EdcbSRJakW/W81c6BddCBcomNCHxevsXYKtunwEwXvPwCEbnKgTVJqcu5iUTD4KbS6qc7Nqrey0sE8DqcvaixoLhqpj6QicnVfzp3lld0cmdl7GYtZp6RszmauxsmySgUhJkbANnTmhpXw7P41e8dCazfNFmMO4Hxeg75C9KRIHt4pmDJB2zXtHz55L1Nmv1ybWZ+FPG47YVrf4ehNuXR2WaY3PsG7pJBrKH54vSDIZJqW7XpMMpMU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
